CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

ALTER TABLE users
    DROP COLUMN authorities;

ALTER TABLE users
    ALTER COLUMN is_active SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN is_non_locked SET NOT NULL;