spring:
  config:
    import: optional:secrets.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-wispy-wind-97919880.eu-central-1.aws.neon.tech:5432/neondb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: smalecbartlomiej
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
    defer-datasource-initialization: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: smalecbartlomiej
    baseline-description: 'init'
    baseline-version: 0
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'

frontend:
  url: 'http://localhost:5173'
