spring:
  datasource:
    password: 7GeDY9kyKBPr
  flyway:
    password: 7GeDY9kyKBPr
jwt:
  secret: 'FdMSpY6dNFlEF3zHVhhIkXEZ0udQCdyzQslxnO9n'
email:
  username: 'smalecbartlomiej@outlook.com'
  password: 'topsecret'